apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-test
spec:
  selector:
    matchLabels:
      app: lb-test
  template:
    metadata:
      labels:
        app: lb-test
    spec:
      containers:
      - name: lb-container
        image: jinsgjg/jenkins-lb-example:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-pull-secret