apiVersion: v1
kind: Service
metadata:
  name: test-apache
spec:
  type: NodePort
  selector:
    app: test-apache
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-apache
spec:
  selector:
    matchLabels:
      app: test-apache
  template:
    metadata:
      labels:
        app: test-apache
    spec:
      containers:
      - name: apache-container
        image: jinsgjg/jenkins-apache2-example:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-pull-secret